### ISSUE TITLE
Multi-Node/Clustered ETCD

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/etcd-druid#107]
# Stories
Please provide stories that we plan to tackle:
- As operator ...
- As provider ...

# Motivation
We should support provisioning and management of multi-node etcd clusters via etcd-druid to serve the following goals:
- Generally, better robustness, resilience, and high availability (HA)
- Zero downtime maintenance (ZDM)
- Non-disruptive scaling
- Single-zone outage/fault tolerance
- Ephemeral (or in-memory) persistence for better performance

# Acceptance Criteria
- [x] First increment (please break-down into different increments rather than by component, if possible)
  <details open>
  <summary>Tasks</summary>

  - [x] Documentation/Proposal
    - [x] gardener/etcd-backup-restore#115
    - [x] gardener/etcd-backup-restore#152
    - [x] gardener/etcd-backup-restore#496

  - [x] Etcd-Druid
    - [x] gardener/etcd-backup-restore#168
    - [x] gardener/etcd-backup-restore#151
    - [x] gardener/etcd-backup-restore#165
    - [x] gardener/etcd-backup-restore#235
    - [x] gardener/etcd-backup-restore#349 
    - [x] gardener/etcd-backup-restore#158
    - [x]  gardener/etcd-backup-restore#354
    - [x] gardener/etcd-backup-restore#340
    - [x] gardener/etcd-backup-restore#358  
    - [x] gardener/etcd-backup-restore#221
    - [x] gardener/etcd-backup-restore#242
    - [x] gardener/etcd-backup-restore#436
    - [x]  gardener/etcd-backup-restore#437
    - [x] gardener/etcd-backup-restore#368
    - [x] gardener/etcd-backup-restore#371
    - [x] gardener/etcd-backup-restore#251
    - [x] gardener/etcd-backup-restore#147
    - [x] gardener/etcd-backup-restore#286

  - [x] Etcd-Backup-Restore
    - [x] https://github.com/gardener/etcd-backup-restore/issues/333
    - [x]  https://github.com/gardener/etcd-backup-restore/issues/321
    - [x] https://github.com/gardener/etcd-backup-restore/issues/354
    - [x] https://github.com/gardener/etcd-backup-restore/issues/322
    - [x] https://github.com/gardener/etcd-backup-restore/issues/489
    - [x] https://github.com/gardener/etcd-backup-restore/issues/323
    - [x] https://github.com/gardener/etcd-wrapper/issues/7

  - [x] Additional Improvements
    - [x] gardener/etcd-backup-restore#280 

  </details>

# Enhancement/Implementation Proposal (optional)
- https://github.com/gardener/etcd-druid/tree/master/docs/proposals/multi-node
