### ISSUE TITLE
☂️  Replace etcd-custom-image with etcd-wrapper

### ISSUE THREAD

**Issue by unmarshall** [gardener/etcd-druid#609]
# How to categorize this issue?
/kind enhancement

## What would you like to be added
`etcd-custom-image` is going to be removed. See [Issue](https://github.com/gardener/etcd-custom-image/issues/16) and the respective [PR](https://github.com/gardener/etcd-wrapper/pull/3).

- [x] Change image vector override for druid
- [x] Change the [command](https://github.com/gardener/etcd-druid/blob/master/pkg/component/etcd/statefulset/values_helper.go#L132-L134) and args that are now passed to the new etcd-wrapper image (component-statefulset)
- [x] Change everywhere `eu.gcr.io/gardener-project/gardener/etcd` is being referenced
   - [x] [test/utils/etcd.go](https://github.com/gardener/etcd-druid/blob/b6b2a0e6177cf9efee6ce6c0c817432f21afc81a/test/utils/etcd.go#L43)
   - [x] [api/v1alpha1/types_etcd_test.go](https://github.com/gardener/etcd-druid/blob/b6b2a0e6177cf9efee6ce6c0c817432f21afc81a/api/v1alpha1/types_etcd_test.go#L172)
   - [x] [component/etcd/statefulset/statefulset_test.go](https://github.com/gardener/etcd-druid/blob/b6b2a0e6177cf9efee6ce6c0c817432f21afc81a/pkg/component/etcd/statefulset/statefulset_test.go#L64)

# Motivation (Why is this needed?)
See the reasons captured in [Issue](https://github.com/gardener/etcd-custom-image/issues/16)

# Acceptance Criteria
Run e2e tests and g/g tests with etcd-wrapper instead of etcd-custom-image and all tests should pass.

**Comment by ishan16696** [comment]
I would like to add/suggest one more thing as acceptance criteria:
We should be able to mimic every possible condition/scenario via ephemeral containers for debugging purposes of etcd cluster as one of such requirement I mentioned here https://github.com/gardener/etcd-wrapper/pull/3#discussion_r1206613906

**Comment by shreyas-s-rao** [comment]
> Change README to reflect the image change

@unmarshall etcd-druid does not mention etcd-custom-image anywhere in the repo, except in the `charts/images.yaml` file, which will anyway be replaced by etcd-wrapper. I think adding this change to the README should be part of an overall overhaul of the druid docs, and should not be a subtask for this umbrella issue. WDYT?

**Comment by unmarshall** [comment]
>I think adding this change to the README should be part of an overall overhaul of the druid docs, and should not be a subtask for this umbrella issue. WDYT?

Ok that is fine. We do not have to do this now.
