### ISSUE TITLE
☂️ [Epic]: Switch to Distroless images for etcd-wrapper and etcd-backup-restore

### ISSUE THREAD

**Issue by unmarshall** [gardener/etcd-druid#612]
# How to categorize this issue?
/kind enhancement

# Stories
This issue will track all activities for the following stories:
- Replacing `etcd-custom-image` with `etcd-wrapper` which now uses distroless image
- Moving to distroless for etcdbr
- Changes required in `etcd-druid` to adapt to the new images
- Changes required in druid e2e tests which now gets impacted due to use of distroless images
- Testing all use cases from an operator standpoint with ephemeral container

# Motivation (Why is this needed?)
The decision to move to distroless images for etcd-backup-restore and also etcd-wrapper (replacement for etcd-custom-image) has resulted in changes that needs to be made to druid. This issue will be used to track all activities to make this happen.

# Acceptance Criteria

- [x] https://github.com/gardener/etcd-custom-image/issues/16  (**PR:** https://github.com/gardener/etcd-wrapper/pull/3)
- [x] https://github.com/gardener/etcd-backup-restore/issues/635
- [x] https://github.com/gardener/etcd-druid/issues/609
- [x] https://github.com/gardener/etcd-druid/issues/554

**Comment by aaronfern** [comment]
Closing this issue as all acceptance criteria has been met
/close
